#!/usr/bin/env ruby

base_dir = File.dirname(__FILE__)

unless File.exists?(File.join(base_dir, '..', 'dist', 'ember-simple-auth.js'))
  puts "\n** dist/ember-simple-auth.js doesn't exist, building it first...\n\n"
  `cd .. && bundle && bundle exec rake ember:test`
end

require 'rubygems'
require 'bundler'

Bundler.require

# serves the main template (see bottom of this file)
get '/' do
  erb :index
end

# serve the JS file from the /dist directory
get '/ember-simple-auth.js' do
  File.read(File.join(base_dir, '..', 'dist', 'ember-simple-auth.js'))
end

# serve the HTML files from the respective example directoy
%w(1-simple 2-errors 3-ember-data 4-full).each do |example|
  get "/#{example}" do
    erb File.read(File.join(base_dir, example, 'index.html'))
  end
end

# session creation endpoint; successfull if credentials are letme/in
post '/session' do
  payload = request.body.read
  json    = JSON.parse(payload)
  if json['session']['identification'] == 'letme' && json['session']['password'] == 'in'
    [200, { 'Content-Type' => 'application/json' }, ['{ "session": { "authToken": "secret token!" } }']]
  else
    [422, { 'Content-Type' => 'application/json' }, ['{ "error": "invalid credentials" }']]
  end
end

# session deletion endpoint
delete '/session' do
  [200, { 'Content-Type' => 'application/json' }, ['']]
end

# posts endpoint; successful if a valid authentication token header is sent
get '/posts' do
  if env['HTTP_X_AUTHENTICATION_TOKEN'] == 'secret token!'
    [200, { 'Content-Type' => 'application/json' }, ['{ "posts": [{ "id": 1, "title": "first post", "body": "some content"}, { "id": 2, "title": "2nd post", "body": "some other body" }] }']]
  else
    [401, {}, ['']]
  end
end

# account endpoint; successful if a valid authentication token header is sent
get '/accounts/1' do
  if env['HTTP_X_AUTHENTICATION_TOKEN'] == 'secret token!'
    [200, { 'Content-Type' => 'application/json' }, ['{ "account": { "id": 1, "login": "letme", "name": "Some Person"} }']]
  else
    [401, {}, ['']]
  end
end

# session creation endpoint with custom response; successfull if credentials are letme/in
post '/v2/session' do
  payload = request.body.read
  json    = JSON.parse(payload)
  if json['session']['identification'] == 'letme' && json['session']['password'] == 'in'
    [200, { 'Content-Type' => 'application/json' }, ['{ "TOKEN": "secret token!", "AUTHENTICATED_USER": { "ID": 1 } }']]
  else
    [422, { 'Content-Type' => 'application/json' }, ['{ "MSG": "invalid credentials" }']]
  end
end

# session deletion endpoint for V2
delete '/v2/session' do
  [200, { 'Content-Type' => 'application/json' }, ['']]
end

__END__

@@ layout
<!DOCTYPE html>
<html>
  <head>
    <title>ember-simple-auth - examples</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/1.0.0/handlebars.js"></script>
    <script src="http://builds.emberjs.com/release/ember.js"></script>
    <script src="ember-simple-auth.js"></script>
  </head>
  <body style="padding-top: 50px;">
    <%= yield %>
    <% unless request.path_info == '/' %>
      <nav class="navbar navbar-default navbar-fixed-bottom">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">&larr; back to examples list</a>
        </div>
      </nav>
    <% end %>
  </body>
</html>

@@ index
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="list-group">
        <a href="/1-simple" class="list-group-item">
          <h4 class="list-group-item-heading">Simple example</h4>
          <p class="list-group-item-text">Simple example with only basic authnetication - no error handling, no data, no session account etc.</p>
        </a>
        <a href="/2-errors" class="list-group-item">
          <h4 class="list-group-item-heading">Example with error handling</h4>
          <p class="list-group-item-text">Simple example with error handling - still no data, no session account etc.</p>
        </a>
        <a href="/3-ember-data" class="list-group-item">
          <h4 class="list-group-item-heading">ember-data example</h4>
          <p class="list-group-item-text">Example with error handling and authnenticated ember-data requests - no session account</p>
        </a>
        <a href="/4-full" class="list-group-item">
          <h4 class="list-group-item-heading">Full-fledged example</h4>
          <p class="list-group-item-text">Full-fledged example with error handling, ember-data, session account and custom server responses.</p>
        </a>
      </div>
    </div>
  </div>
</div>
<script>
  delete sessionStorage.authToken;
  delete sessionStorage.account;
</script>