# For every push to the master branch, this checks if the release-plan was
# updated and if it was it will publish stable npm packages based on the
# release plan

name: Publish Stable

env:
  VOLTA_FEATURE_PNPM: 1

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: publish-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-plan:
    name: "Check Release Plan"
    runs-on: ubuntu-latest
    outputs:
      command: ${{ steps.check-release.outputs.command }}

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: 'master'
      # This will only cause the `check-plan` job to have a result of `success`
      # when the .release-plan.json file was changed on the last commit. This
      # plus the fact that this action only runs on main will be enough of a guard
      - id: check-release
        run: if git diff --name-only HEAD HEAD~1 | grep -w -q ".release-plan.json"; then echo "command=release"; fi >> $GITHUB_OUTPUT

  publish:
    name: "NPM Publish"
    runs-on: ubuntu-latest
    needs: check-plan
    if: needs.check-plan.outputs.command == 'release'
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4
      - run: pnpm install --frozen-lockfile
      - name: Set publishing config
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: npm publish
        run: pnpm release-plan publish
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
